//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DloadOrganizer.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("DloadOrganizer.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Example config created. Change it to your needs and run program again..
        /// </summary>
        internal static string ConfigFileCreated {
            get {
                return ResourceManager.GetString("ConfigFileCreated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Configuration file has errors.
        /// </summary>
        internal static string ConfigFileErrors {
            get {
                return ResourceManager.GetString("ConfigFileErrors", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Configuration file not loaded.
        /// </summary>
        internal static string ConfigNotLoaded {
            get {
                return ResourceManager.GetString("ConfigNotLoaded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Press a key to exit....
        /// </summary>
        internal static string PressKeyToExit {
            get {
                return ResourceManager.GetString("PressKeyToExit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No rules defined..
        /// </summary>
        internal static string ValidationNoRules {
            get {
                return ResourceManager.GetString("ValidationNoRules", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Source directory is not set..
        /// </summary>
        internal static string ValidationNoSourceDir {
            get {
                return ResourceManager.GetString("ValidationNoSourceDir", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to At least one rule has no file extensions.
        /// </summary>
        internal static string ValidationRuleNoExtensions {
            get {
                return ResourceManager.GetString("ValidationRuleNoExtensions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to At least one rule has no targets set..
        /// </summary>
        internal static string ValidationRuleNoTarget {
            get {
                return ResourceManager.GetString("ValidationRuleNoTarget", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to At least one rule has a target folder that doesn&apos;t exist.
        /// </summary>
        internal static string ValidationRuleTargetNotExist {
            get {
                return ResourceManager.GetString("ValidationRuleTargetNotExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Source directory doesn&apos;t exist.
        /// </summary>
        internal static string ValidationSourcetDirNotExist {
            get {
                return ResourceManager.GetString("ValidationSourcetDirNotExist", resourceCulture);
            }
        }
    }
}
